name: MyGitHubAction

on:
  push:

jobs:
  my_testing:
    runs-on: ubuntu-latest

    steps:
    - name: Git clone my repository
      uses: actions/checkout@v1
      
    - name: Install python
      uses: actions/setup-python@v1
      with:
        python-version: '3.10'
        architecture: 'x64'
    
    - name: Install pytest
      run: pip install pytest
      
    - name: View repository files
      run: ls -a
      
#     - name: Python Style Checker
#       uses: andymckay/pycodestyle-action@0.1.3
      
    - name: Run tests
      run: |
          cd test
          pytest -v -s test.py
